- animation-effect: fadeInRight
  icon: fa-laptop
  heading: Development
  description: We have experience in all facets of development to help our clients reach their full potential. We Automate your business online, to get more sales and profits.
  link: development

- animation-effect: fadeInLeft
  icon: fa-briefcase
  heading: Digital Marketing
  description: Our purpose is to empower digital relationships through mobility. We do all types of marketing like Email Marketing, Social Marketing, Search Engine Optimization, Content Marketing.
  link: digital-marketing

- animation-effect: fadeInRight
  icon: fa-pencil
  heading: Design
  description: We specialize in graphic design for promotional displays, packaging, marketing brochures, billboards, presentation folders, logo design and business card design for your business, products and services.
  link: design

- animation-effect: fadeInLeft
  icon: fa-user
  heading: Testing and Automation
  description: The objective of automated testing is to simplify as much of the testing effort as possible with a minimum set of scripts. If unit testing consumes a large percentage of a quality assurance (QA) team's resources.
  link: testing
